#!/usr/bin/python3

# Copyright (c) 2020 Stanford University
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# This cperf benchmark compares the performance of Homa with TCP.
# Type "cp_vs_tcp --help" for documentation.

from cperf import *

DEFAULTS_25G = {
    "client_ports":        3,
    "port_receivers":      3,
    "port_threads":        3,
    "server_ports":        3,
    "tcp_client_ports":    4,
    "tcp_port_receivers":  1,
    "tcp_port_threads":    1,
    "tcp_server_ports":    8,
}

load_info = [["w2", 3.2], ["w3", 14], ["w4", 20], ["w5", 20]]

def save_plot_with_side_legend(ax, path, legend_y=1.0):
    fig = ax.figure
    legend = ax.legend(loc="upper left", bbox_to_anchor=(1.02, legend_y),
            borderaxespad=0.0, prop={'size': 9})
    fig.set_size_inches(12, 5)
    fig.tight_layout(rect=(0, 0, 0.93, 1))
    fig.savefig(path, bbox_inches="tight",
            bbox_extra_artists=[legend] if legend else None)

parser = get_parser(description=
        'Measures slowdown as a function of message size for Homa and TCP.',
        usage='%(prog)s [options]')
parser.set_defaults(**DEFAULTS_25G)
parser.add_argument('--tcp', dest='tcp', type=boolean,
        default=True, help="Boolean value: indicates whether measurements "
                "should be run on TCP (default: true)")
parser.add_argument('--dctcp', dest='dctcp', type=boolean,
        default=False, help="Boolean value:: indicates whether measurements "
                "should be run on DCTCP (default: false)")
parser.add_argument('--servers', dest='num_servers', type=int, metavar='count',
        default=0, help="If nonzero, clients and servers will be segregated "
        "and this value indicates the number of server nodes; all other "
        "nodes will be clients. If 0, each node runs both a client and a "
        "server (default: 0)")
options = parser.parse_args()
init(options)
if options.num_servers <= 0:
    servers = range(0, options.num_nodes)
    clients = range(0, options.num_nodes)
    options.num_clients = options.num_nodes;
    options.num_servers = options.num_nodes;
    bw_multiplier = 0.5
else:
    if options.num_servers >= options.num_nodes:
        raise Error("Illegal value %d for --servers option; must be less "
                "than --nodes (%d)" % (options.num_servers, options.num_nodes))
    options.num_clients = options.num_nodes - options.num_servers
    servers = range(0, options.num_servers)
    clients = range(options.num_servers, options.num_nodes)
    bw_multiplier = min(options.num_servers, options.num_clients) \
            / options.num_clients;

if options.workload != "":
    load_info = [[options.workload, options.gbps]];

# First, run all of the experiments
if not options.plot_only:
    congestion = get_sysctl_parameter("net.ipv4.tcp_congestion_control")
    tcp_fastopen = get_sysctl_parameter("net.ipv4.tcp_fastopen")
    tcp_ecn = get_sysctl_parameter("net.ipv4.tcp_ecn")
    for workload, bw in load_info:
        options.workload = workload
        options.gbps = bw * bw_multiplier
        unloaded_exp = "unloaded_" + workload;
        homa_exp = "homa_" + workload;
        tcp_exp = "tcp_" + workload;
        dctcp_exp = "dctcp_" + workload;
        try:
            options.protocol = "homa"
            start_servers(range(1, 2), options)

            o = copy.deepcopy(options);
            o.gbps = 0.0
            o.client_ports = 1
            o.client_max = 1
            o.server_ports = 1
            o.server_nodes = 1
            o.first_server = 1
            o.unloaded = 500
            run_experiment(unloaded_exp, range(0, 1), o)

            start_servers(servers, options)
            run_experiment(homa_exp, clients, options)

            if options.tcp:
                options.protocol = "tcp"
                options.tcp_fastopen = False
                options.tcp_http2 = False
                options.tcp_http2_sessions = 1
                options.tcp_client_pooling = False
                options.tcp_pool_size = 1
                set_sysctl_parameter("net.ipv4.tcp_congestion_control",
                        "cubic", range(0, options.num_nodes))
                set_sysctl_parameter("net.ipv4.tcp_ecn", "0",
                        range(0, options.num_nodes))
                set_sysctl_parameter("net.ipv4.tcp_fastopen", "0",
                        range(0, options.num_nodes))
                start_servers(servers, options)
                run_experiment(tcp_exp, clients, options)

            if options.dctcp:
                options.protocol = "tcp"
                options.tcp_fastopen = False
                options.tcp_http2 = False
                options.tcp_http2_sessions = 1
                options.tcp_client_pooling = False
                options.tcp_pool_size = 1
                set_sysctl_parameter("net.ipv4.tcp_congestion_control",
                        "dctcp", range(0, options.num_nodes))
                set_sysctl_parameter("net.ipv4.tcp_ecn", "1",
                        range(0, options.num_nodes))
                set_sysctl_parameter("net.ipv4.tcp_fastopen", "0",
                        range(0, options.num_nodes))
                start_servers(servers, options)
                run_experiment(dctcp_exp, clients, options)
        except Exception as e:
            log(traceback.format_exc())

    if options.tcp or options.dctcp:
        print("Resetting TCP congestion control to %s" % (congestion))
        set_sysctl_parameter("net.ipv4.tcp_congestion_control", congestion,
                range(0, options.num_nodes))
        set_sysctl_parameter("net.ipv4.tcp_fastopen", tcp_fastopen,
                range(0, options.num_nodes))
        set_sysctl_parameter("net.ipv4.tcp_ecn", tcp_ecn,
                range(0, options.num_nodes))
    log("Stopping nodes")
    stop_nodes()
    scan_logs()

# Generate plots and reports
for workload, bw in load_info:
    unloaded_exp = "unloaded_" + workload;
    homa_exp = "homa_" + workload;
    tcp_exp = "tcp_" + workload;
    dctcp_exp = "dctcp_" + workload;

    set_unloaded(unloaded_exp)

    # Generate slowdown plot.
    log("Generating slowdown plot for %s" % (workload))
    title = "%s %d nodes, %.1f Gbps" % (workload.capitalize(),
            options.num_nodes, bw)
    ax = start_slowdown_plot(title, 10000, homa_exp)
    if options.tcp:
        plot_slowdown(ax, tcp_exp, "p99", "TCP P99", color=tcp_color)
        plot_slowdown(ax, tcp_exp, "p50", "TCP P50", color=tcp_color2)
    if options.dctcp:
        plot_slowdown(ax, dctcp_exp, "p99", "DCTCP P99", color=dctcp_color)
        plot_slowdown(ax, dctcp_exp, "p50", "DCTCP P50", color=dctcp_color2)
    plot_slowdown(ax, homa_exp, "p99", "Homa P99", color=homa_color)
    plot_slowdown(ax, homa_exp, "p50", "Homa P50", color=homa_color2)
    save_plot_with_side_legend(ax,
            "%s/reports/vs_tcp_%s.pdf" % (options.log_dir, workload))

    log("Generating P50 slowdown plot for %s" % (workload))
    ax = start_slowdown_plot(title + " P50", 10000, homa_exp)
    if options.tcp:
        plot_slowdown(ax, tcp_exp, "p50", "TCP P50", color=tcp_color2)
    if options.dctcp:
        plot_slowdown(ax, dctcp_exp, "p50", "DCTCP P50", color=dctcp_color2)
    plot_slowdown(ax, homa_exp, "p50", "Homa P50", color=homa_color2)
    save_plot_with_side_legend(ax,
            "%s/reports/vs_tcp_%s_p50.pdf" % (options.log_dir, workload))

    log("Generating P99 slowdown plot for %s" % (workload))
    ax = start_slowdown_plot(title + " P99", P99_SLOWDOWN_MAX, homa_exp)
    if options.tcp:
        plot_slowdown(ax, tcp_exp, "p99", "TCP P99", color=tcp_color)
    if options.dctcp:
        plot_slowdown(ax, dctcp_exp, "p99", "DCTCP P99", color=dctcp_color)
    plot_slowdown(ax, homa_exp, "p99", "Homa P99", color=homa_color)
    save_plot_with_side_legend(ax,
            "%s/reports/vs_tcp_%s_p99.pdf" % (options.log_dir, workload))

    # Generate CDF of small-message RTTs.
    log("Generating short message CDF for %s" % (workload))
    unloaded_x, unloaded_y = get_short_cdf(unloaded_exp)
    homa_x, homa_y = get_short_cdf(homa_exp)
    if options.tcp:
        tcp_x, tcp_y = get_short_cdf(tcp_exp)
    if options.dctcp:
        dctcp_x, dctcp_y = get_short_cdf(dctcp_exp)
    start_cdf_plot(title, 10, 0.99e05, 1e-05, "RTT (usecs)",
            "Cumulative Fraction Short Messages")
    if options.tcp:
        plt.plot(tcp_x, tcp_y, label="TCP", color=tcp_color)
    if options.dctcp:
        plt.plot(dctcp_x, dctcp_y, label="DCTCP", color=dctcp_color)
    plt.plot(homa_x, homa_y, label="Homa", color=homa_color)
    plt.plot(unloaded_x, unloaded_y, label="Homa best case", color=unloaded_color)
    ax = plt.gca()
    save_plot_with_side_legend(ax,
            "%s/reports/short_cdf_%s.pdf" % (options.log_dir, workload))
