#!/usr/bin/env bash
set -euo pipefail

LOCAL_USER="$(whoami)"
REMOTE_USER="${CLOUDLAB_USER:-$LOCAL_USER}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOSTS_FILE="$SCRIPT_DIR/hosts_5.txt"
SSH_DIR="$HOME/.ssh"
CONFIG_DIR="$SSH_DIR/config.d"
LOCAL_CONFIG_FILE="$CONFIG_DIR/cloudlab"
REPO_URL="${HOMA_REPO_URL:-https://github.com/XanderYoon/HomaModule.git}"
REPO_BRANCH="${HOMA_REPO_BRANCH:-main}"
REMOTE_REPO_DIR="${REMOTE_REPO_DIR:-\$HOME/HomaModule}"
NODE0_ALIAS="node0"

log() {
    printf '\n[%s] %s\n' "$1" "$2"
}

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Missing required command: $1" >&2
        exit 1
    fi
}

read_hosts() {
    if [[ ! -f "$HOSTS_FILE" ]]; then
        echo "hosts_5.txt not found at $HOSTS_FILE" >&2
        exit 1
    fi

    mapfile -t HOSTS < <(awk 'NF && $1 !~ /^#/' "$HOSTS_FILE")
    if [[ "${#HOSTS[@]}" -ne 5 ]]; then
        echo "Expected exactly 5 hosts in $HOSTS_FILE, found ${#HOSTS[@]}" >&2
        exit 1
    fi
}

ensure_local_key() {
    mkdir -p "$SSH_DIR" "$CONFIG_DIR"
    chmod 700 "$SSH_DIR"

    if [[ ! -f "$SSH_DIR/id_ed25519" ]]; then
        ssh-keygen -t ed25519 -f "$SSH_DIR/id_ed25519" -N ""
    fi
}

write_local_ssh_config() {
    cat >"$LOCAL_CONFIG_FILE" <<EOF
# Auto-generated by ssh_setup/ssh_setup_5nodes.sh
EOF

    for i in "${!HOSTS[@]}"; do
        cat >>"$LOCAL_CONFIG_FILE" <<EOF
Host node$i node-$i cloudlab-node$i cloudlab-node-$i
    HostName ${HOSTS[$i]}
    User $REMOTE_USER
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

EOF
    done

    touch "$SSH_DIR/config"
    if ! grep -Fqx "Include $CONFIG_DIR/*" "$SSH_DIR/config"; then
        printf 'Include %s/*\n' "$CONFIG_DIR" >>"$SSH_DIR/config"
    fi
}

install_local_key_on_nodes() {
    for i in "${!HOSTS[@]}"; do
        log "local-ssh" "Installing local SSH key on node$i (${HOSTS[$i]})"
        ssh-copy-id -o StrictHostKeyChecking=no "$REMOTE_USER@${HOSTS[$i]}"
    done
}

verify_local_connectivity() {
    for i in "${!HOSTS[@]}"; do
        log "local-verify" "Verifying local SSH to node$i"
        ssh "node$i" "hostname"
    done
}

prepare_node0_ssh() {
    log "node0-ssh" "Preparing SSH key and config on node0"
    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        mkdir -p ~/.ssh ~/.ssh/config.d
        chmod 700 ~/.ssh
        if [[ ! -f ~/.ssh/id_ed25519 ]]; then
            ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
        fi
    '

    ssh "$NODE0_ALIAS" "cat > ~/.ssh/config.d/cloudlab" <<EOF
# Auto-generated by ssh_setup/ssh_setup_5nodes.sh
EOF

    for i in "${!HOSTS[@]}"; do
        ssh "$NODE0_ALIAS" "cat >> ~/.ssh/config.d/cloudlab" <<EOF
Host node$i node-$i cloudlab-node$i cloudlab-node-$i
    HostName ${HOSTS[$i]}
    User $REMOTE_USER
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

EOF
    done

    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        touch ~/.ssh/config
        if ! grep -Fqx "Include ~/.ssh/config.d/*" ~/.ssh/config; then
            printf "Include ~/.ssh/config.d/*\n" >> ~/.ssh/config
        fi
        chmod 600 ~/.ssh/config ~/.ssh/config.d/cloudlab
    '
}

install_node0_key_on_peers() {
    local node0_pubkey
    node0_pubkey="$(ssh "$NODE0_ALIAS" "cat ~/.ssh/id_ed25519.pub")"

    for i in $(seq 1 4); do
        log "node0-key" "Authorizing node0 SSH key on node$i"
        ssh "node$i" "
            set -euo pipefail
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            if ! grep -Fqx '$node0_pubkey' ~/.ssh/authorized_keys; then
                printf '%s\n' '$node0_pubkey' >> ~/.ssh/authorized_keys
            fi
        "
    done
}

verify_node0_connectivity() {
    for i in $(seq 1 4); do
        log "node0-verify" "Verifying node0 SSH to node$i"
        ssh "$NODE0_ALIAS" "ssh node$i hostname"
    done
}

setup_homa_on_node0() {
    log "node0-homa" "Installing packages on node0"
    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y git make gcc g++ openssh-client ethtool python3
    '

    log "node0-homa" "Cloning or updating Homa repo on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        if [[ -d $REMOTE_REPO_DIR/.git ]]; then
            git -C $REMOTE_REPO_DIR fetch origin $REPO_BRANCH
            git -C $REMOTE_REPO_DIR checkout $REPO_BRANCH
            git -C $REMOTE_REPO_DIR reset --hard origin/$REPO_BRANCH
        else
            rm -rf -- $REMOTE_REPO_DIR
            git clone --branch $REPO_BRANCH $REPO_URL $REMOTE_REPO_DIR
        fi
    "

    log "node0-homa" "Building Homa utilities on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        cd $REMOTE_REPO_DIR/util
        make clean
        make
        mkdir -p ~/bin
        install -m 755 $REMOTE_REPO_DIR/util/cp_node ~/bin/cp_node
        install -m 755 $REMOTE_REPO_DIR/util/homa_prio ~/bin/homa_prio
    "
}

verify_homa_on_node0() {
    log "node0-homa" "Verifying Homa utilities on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        test -x $REMOTE_REPO_DIR/util/cp_node
        test -x $REMOTE_REPO_DIR/util/homa_prio
        printf 'Remote repo: %s\n' $REMOTE_REPO_DIR
        printf 'cp_node: %s\n' $REMOTE_REPO_DIR/util/cp_node
        printf 'homa_prio: %s\n' $REMOTE_REPO_DIR/util/homa_prio
    "
}

enable_dctcp_and_tfo() {
    for i in "${!HOSTS[@]}"; do
        log "tcp-tuning" "Enabling DCTCP and TCP Fast Open on node$i"
        ssh "node$i" '
            set -euo pipefail
            sudo modprobe tcp_dctcp || true
            sudo sysctl -w net.ipv4.tcp_ecn=1
            sudo sysctl -w net.ipv4.tcp_congestion_control=dctcp
            sudo sysctl -w net.ipv4.tcp_fastopen=3
        '
    done
}

verify_dctcp_and_tfo() {
    for i in "${!HOSTS[@]}"; do
        log "tcp-verify" "Verifying DCTCP and TCP Fast Open on node$i"
        ssh "node$i" '
            set -euo pipefail
            printf "tcp_ecn=%s\n" "$(sysctl -n net.ipv4.tcp_ecn)"
            printf "tcp_congestion_control=%s\n" \
                "$(sysctl -n net.ipv4.tcp_congestion_control)"
            printf "tcp_fastopen=%s\n" "$(sysctl -n net.ipv4.tcp_fastopen)"
        '
    done
}

main() {
    require_cmd ssh
    require_cmd ssh-copy-id
    require_cmd ssh-keygen
    require_cmd awk

    read_hosts
    ensure_local_key
    write_local_ssh_config
    install_local_key_on_nodes
    verify_local_connectivity
    prepare_node0_ssh
    install_node0_key_on_peers
    verify_node0_connectivity
    setup_homa_on_node0
    verify_homa_on_node0
    enable_dctcp_and_tfo
    verify_dctcp_and_tfo

    log "done" "5-node SSH bootstrap complete, Homa utilities are built on node0, and TCP tuning is enabled"
}

main "$@"
