#!/usr/bin/env bash
set -euo pipefail

LOCAL_USER="$(whoami)"
REMOTE_USER="${CLOUDLAB_USER:-$LOCAL_USER}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOSTS_FILE="$SCRIPT_DIR/hosts.txt"
SSH_DIR="$HOME/.ssh"
CONFIG_DIR="$SSH_DIR/config.d"
LOCAL_CONFIG_FILE="$CONFIG_DIR/cloudlab"
REPO_URL="${HOMA_REPO_URL:-https://github.com/XanderYoon/HomaModule.git}"
REMOTE_REPO_DIR="${REMOTE_REPO_DIR:-\$HOME/HomaModule}"
NODE0_ALIAS="node0"

log() {
    printf '\n[%s] %s\n' "$1" "$2"
}

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Missing required command: $1" >&2
        exit 1
    fi
}

read_hosts() {
    if [[ ! -f "$HOSTS_FILE" ]]; then
        echo "hosts.txt not found at $HOSTS_FILE" >&2
        exit 1
    fi

    mapfile -t HOSTS < <(awk 'NF && $1 !~ /^#/' "$HOSTS_FILE")
    if [[ "${#HOSTS[@]}" -ne 10 ]]; then
        echo "Expected exactly 10 hosts in $HOSTS_FILE, found ${#HOSTS[@]}" >&2
        exit 1
    fi
}

ensure_local_key() {
    mkdir -p "$SSH_DIR" "$CONFIG_DIR"
    chmod 700 "$SSH_DIR"

    if [[ ! -f "$SSH_DIR/id_ed25519" ]]; then
        ssh-keygen -t ed25519 -f "$SSH_DIR/id_ed25519" -N ""
    fi
}

write_local_ssh_config() {
    cat >"$LOCAL_CONFIG_FILE" <<EOF
# Auto-generated by experiments/ssh_setup.sh
EOF

    for i in "${!HOSTS[@]}"; do
        cat >>"$LOCAL_CONFIG_FILE" <<EOF
Host node$i cloudlab-node$i
    HostName ${HOSTS[$i]}
    User $REMOTE_USER
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

EOF
    done

    touch "$SSH_DIR/config"
    if ! grep -Fqx "Include $CONFIG_DIR/*" "$SSH_DIR/config"; then
        printf 'Include %s/*\n' "$CONFIG_DIR" >>"$SSH_DIR/config"
    fi
}

install_local_key_on_nodes() {
    for i in "${!HOSTS[@]}"; do
        log "local-ssh" "Installing local SSH key on node$i (${HOSTS[$i]})"
        ssh-copy-id -o StrictHostKeyChecking=no "$REMOTE_USER@${HOSTS[$i]}"
    done
}

verify_local_connectivity() {
    for i in "${!HOSTS[@]}"; do
        log "local-verify" "Verifying local SSH to node$i"
        ssh "node$i" "hostname"
    done
}

prepare_node0_ssh() {
    log "node0-ssh" "Preparing SSH key and config on node0"
    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        mkdir -p ~/.ssh ~/.ssh/config.d
        chmod 700 ~/.ssh
        if [[ ! -f ~/.ssh/id_ed25519 ]]; then
            ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
        fi
    '

    ssh "$NODE0_ALIAS" "cat > ~/.ssh/config.d/cloudlab" <<EOF
# Auto-generated by experiments/ssh_setup.sh
EOF

    for i in "${!HOSTS[@]}"; do
        ssh "$NODE0_ALIAS" "cat >> ~/.ssh/config.d/cloudlab" <<EOF
Host node$i cloudlab-node$i
    HostName ${HOSTS[$i]}
    User $REMOTE_USER
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

EOF
    done

    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        touch ~/.ssh/config
        if ! grep -Fqx "Include ~/.ssh/config.d/*" ~/.ssh/config; then
            printf "Include ~/.ssh/config.d/*\n" >> ~/.ssh/config
        fi
        chmod 600 ~/.ssh/config ~/.ssh/config.d/cloudlab
    '
}

install_node0_key_on_peers() {
    local node0_pubkey
    node0_pubkey="$(ssh "$NODE0_ALIAS" "cat ~/.ssh/id_ed25519.pub")"

    for i in $(seq 1 9); do
        log "node0-key" "Authorizing node0 SSH key on node$i"
        ssh "node$i" "
            set -euo pipefail
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            if ! grep -Fqx '$node0_pubkey' ~/.ssh/authorized_keys; then
                printf '%s\n' '$node0_pubkey' >> ~/.ssh/authorized_keys
            fi
        "
    done
}

verify_node0_connectivity() {
    for i in $(seq 1 9); do
        log "node0-verify" "Verifying node0 SSH to node$i"
        ssh "$NODE0_ALIAS" "ssh node$i hostname"
    done
}

setup_homa_on_node0() {
    log "node0-homa" "Installing packages on node0"
    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y git make gcc g++ openssh-client ethtool python3 "linux-headers-$(uname -r)"
    '

    log "node0-homa" "Cloning or updating Homa repo on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        if [[ -d $REMOTE_REPO_DIR/.git ]]; then
            git -C $REMOTE_REPO_DIR fetch --all --prune
            git -C $REMOTE_REPO_DIR pull --ff-only
        else
            rm -rf $REMOTE_REPO_DIR
            git clone $REPO_URL $REMOTE_REPO_DIR
        fi
    "

    log "node0-homa" "Building Homa kernel module and utilities on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        make -C $REMOTE_REPO_DIR clean
        make -C $REMOTE_REPO_DIR
        make -C $REMOTE_REPO_DIR/util clean
        make -C $REMOTE_REPO_DIR/util
        mkdir -p ~/bin
        install -m 755 $REMOTE_REPO_DIR/util/cp_node ~/bin/cp_node
        install -m 755 $REMOTE_REPO_DIR/util/homa_prio ~/bin/homa_prio
    "

    log "node0-homa" "Loading Homa on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        sudo rmmod homa >/dev/null 2>&1 || true
        sudo insmod $REMOTE_REPO_DIR/homa.ko
        sudo sysctl net.homa.link_mbps=25000
        sudo sysctl net.homa.num_priorities=8
    "
}

verify_homa_on_node0() {
    log "node0-homa" "Verifying Homa artifacts on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        test -f $REMOTE_REPO_DIR/homa.ko
        test -x $REMOTE_REPO_DIR/util/cp_node
        test -x $REMOTE_REPO_DIR/util/homa_prio
        lsmod | grep '^homa '
        test -r /proc/net/homa_metrics
        printf 'Remote repo: %s\n' $REMOTE_REPO_DIR
        printf 'cp_node: %s\n' $REMOTE_REPO_DIR/util/cp_node
        printf 'homa_prio: %s\n' $REMOTE_REPO_DIR/util/homa_prio
    "
}

main() {
    require_cmd ssh
    require_cmd ssh-copy-id
    require_cmd ssh-keygen
    require_cmd awk

    read_hosts
    ensure_local_key
    write_local_ssh_config
    install_local_key_on_nodes
    verify_local_connectivity
    prepare_node0_ssh
    install_node0_key_on_peers
    verify_node0_connectivity
    setup_homa_on_node0
    verify_homa_on_node0

    log "done" "SSH bootstrap complete and Homa is built and loaded on node0"
}

main "$@"
