#!/usr/bin/env bash
set -euo pipefail

LOCAL_USER="$(whoami)"
REMOTE_USER="${CLOUDLAB_USER:-$LOCAL_USER}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HOSTS_FILE="$SCRIPT_DIR/hosts_10.txt"
SSH_DIR="$HOME/.ssh"
CONFIG_DIR="$SSH_DIR/config.d"
LOCAL_CONFIG_FILE="$CONFIG_DIR/cloudlab"
REPO_URL="${HOMA_REPO_URL:-https://github.com/XanderYoon/HomaModule.git}"
REPO_BRANCH="${HOMA_REPO_BRANCH:-main}"
REMOTE_REPO_DIR="${REMOTE_REPO_DIR:-\$HOME/HomaModule}"
NODE0_ALIAS="node0"

log() {
    printf '\n[%s] %s\n' "$1" "$2"
}

require_cmd() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Missing required command: $1" >&2
        exit 1
    fi
}

read_hosts() {
    if [[ ! -f "$HOSTS_FILE" ]]; then
        echo "hosts_10.txt not found at $HOSTS_FILE" >&2
        exit 1
    fi

    mapfile -t HOSTS < <(awk 'NF && $1 !~ /^#/' "$HOSTS_FILE")
    if [[ "${#HOSTS[@]}" -ne 10 ]]; then
        echo "Expected exactly 10 hosts in $HOSTS_FILE, found ${#HOSTS[@]}" >&2
        exit 1
    fi
}

ensure_local_key() {
    mkdir -p "$SSH_DIR" "$CONFIG_DIR"
    chmod 700 "$SSH_DIR"

    if [[ ! -f "$SSH_DIR/id_ed25519" ]]; then
        ssh-keygen -t ed25519 -f "$SSH_DIR/id_ed25519" -N ""
    fi
}

write_local_ssh_config() {
    cat >"$LOCAL_CONFIG_FILE" <<EOF
# Auto-generated by ssh_setup/ssh_setup_10nodes.sh
EOF

    for i in "${!HOSTS[@]}"; do
        cat >>"$LOCAL_CONFIG_FILE" <<EOF
Host node$i node-$i cloudlab-node$i cloudlab-node-$i
    HostName ${HOSTS[$i]}
    User $REMOTE_USER
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

EOF
    done

    touch "$SSH_DIR/config"
    if ! grep -Fqx "Include $CONFIG_DIR/*" "$SSH_DIR/config"; then
        printf 'Include %s/*\n' "$CONFIG_DIR" >>"$SSH_DIR/config"
    fi
}

install_local_key_on_nodes() {
    for i in "${!HOSTS[@]}"; do
        log "local-ssh" "Installing local SSH key on node$i (${HOSTS[$i]})"
        ssh-copy-id -o StrictHostKeyChecking=no "$REMOTE_USER@${HOSTS[$i]}"
    done
}

verify_local_connectivity() {
    for i in "${!HOSTS[@]}"; do
        log "local-verify" "Verifying local SSH to node$i"
        ssh "node$i" "hostname"
    done
}

prepare_node0_ssh() {
    log "node0-ssh" "Preparing SSH key and config on node0"
    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        mkdir -p ~/.ssh ~/.ssh/config.d
        chmod 700 ~/.ssh
        if [[ ! -f ~/.ssh/id_ed25519 ]]; then
            ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N ""
        fi
    '

    ssh "$NODE0_ALIAS" "cat > ~/.ssh/config.d/cloudlab" <<EOF
# Auto-generated by ssh_setup/ssh_setup_10nodes.sh
EOF

    for i in "${!HOSTS[@]}"; do
        ssh "$NODE0_ALIAS" "cat >> ~/.ssh/config.d/cloudlab" <<EOF
Host node$i node-$i cloudlab-node$i cloudlab-node-$i
    HostName ${HOSTS[$i]}
    User $REMOTE_USER
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null

EOF
    done

    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        touch ~/.ssh/config
        if ! grep -Fqx "Include ~/.ssh/config.d/*" ~/.ssh/config; then
            printf "Include ~/.ssh/config.d/*\n" >> ~/.ssh/config
        fi
        chmod 600 ~/.ssh/config ~/.ssh/config.d/cloudlab
    '
}

install_node0_key_on_peers() {
    local node0_pubkey
    node0_pubkey="$(ssh "$NODE0_ALIAS" "cat ~/.ssh/id_ed25519.pub")"

    for i in $(seq 1 9); do
        log "node0-key" "Authorizing node0 SSH key on node$i"
        ssh "node$i" "
            set -euo pipefail
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            touch ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys
            if ! grep -Fqx '$node0_pubkey' ~/.ssh/authorized_keys; then
                printf '%s\n' '$node0_pubkey' >> ~/.ssh/authorized_keys
            fi
        "
    done
}

verify_node0_connectivity() {
    for i in $(seq 1 9); do
        log "node0-verify" "Verifying node0 SSH to node$i"
        ssh "$NODE0_ALIAS" "ssh node$i hostname"
    done
}

setup_homa_on_node0() {
    log "node0-homa" "Installing packages on node0"
    ssh "$NODE0_ALIAS" '
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y git make gcc g++ openssh-client ethtool python3
    '

    log "node0-homa" "Cloning or updating Homa repo on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        if [[ -d $REMOTE_REPO_DIR/.git ]]; then
            git -C $REMOTE_REPO_DIR fetch origin $REPO_BRANCH
            git -C $REMOTE_REPO_DIR checkout $REPO_BRANCH
            git -C $REMOTE_REPO_DIR reset --hard origin/$REPO_BRANCH
        else
            rm -rf -- $REMOTE_REPO_DIR
            git clone --branch $REPO_BRANCH $REPO_URL $REMOTE_REPO_DIR
        fi
    "

    log "node0-homa" "Building Homa utilities on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        cd $REMOTE_REPO_DIR/util
        make clean
        make
        mkdir -p ~/bin
        /usr/bin/install -m 755 $REMOTE_REPO_DIR/util/cp_node ~/bin/cp_node
        /usr/bin/install -m 755 $REMOTE_REPO_DIR/util/homa_prio ~/bin/homa_prio
    "
}

verify_homa_on_node0() {
    log "node0-homa" "Verifying Homa utilities on node0"
    ssh "$NODE0_ALIAS" "
        set -euo pipefail
        test -x $REMOTE_REPO_DIR/util/cp_node
        test -x $REMOTE_REPO_DIR/util/homa_prio
        printf 'Remote repo: %s\n' $REMOTE_REPO_DIR
        printf 'cp_node: %s\n' $REMOTE_REPO_DIR/util/cp_node
        printf 'homa_prio: %s\n' $REMOTE_REPO_DIR/util/homa_prio
    "
}

configure_dctcp() {
    for i in "${!HOSTS[@]}"; do
        log "dctcp" "Configuring DCTCP on node$i"
        ssh "node$i" '
            set -euo pipefail
            sudo modprobe tcp_dctcp
            sudo sysctl -w net.ipv4.tcp_ecn=1
            sudo sysctl -w net.ipv4.tcp_congestion_control=dctcp
            sudo sysctl -w net.ipv4.tcp_fastopen=0
        '
    done
}

verify_dctcp() {
    for i in "${!HOSTS[@]}"; do
        log "dctcp-verify" "Verifying DCTCP on node$i"
        ssh "node$i" '
            set -euo pipefail
            node_name="$(hostname)"
            ecn="$(sysctl -n net.ipv4.tcp_ecn)"
            cc="$(sysctl -n net.ipv4.tcp_congestion_control)"
            tfo="$(sysctl -n net.ipv4.tcp_fastopen)"
            [[ "$ecn" == "1" ]] || { echo "$node_name: tcp_ecn=$ecn, expected 1" >&2; exit 1; }
            [[ "$cc" == "dctcp" ]] || { echo "$node_name: tcp_congestion_control=$cc, expected dctcp" >&2; exit 1; }
            [[ "$tfo" == "0" ]] || { echo "$node_name: tcp_fastopen=$tfo, expected 0" >&2; exit 1; }
            printf "%s: DCTCP OK\n" "$node_name"
        '
    done
}

configure_xl170_paper_hardware() {
    for i in "${!HOSTS[@]}"; do
        log "xl170-tuning" "Applying xl170 paper hardware settings on node$i"
        ssh "node$i" '
            set -euo pipefail
            iface="ens1f1"
            if [[ ! -d /sys/class/net/$iface ]]; then
                echo "Expected xl170 interface $iface not found on $(hostname)" >&2
                exit 1
            fi
            sudo ip link set dev "$iface" mtu 3000
            sudo ethtool -K "$iface" tso on gso on gro on >/dev/null 2>&1 || true
            if command -v cpupower >/dev/null 2>&1; then
                sudo cpupower frequency-set -g performance >/dev/null 2>&1 || true
            fi
            for f in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
                [[ -e "$f" ]] || continue
                printf "performance\n" | sudo tee "$f" >/dev/null || true
            done
            sudo sysctl -w net.core.rps_sock_flow_entries=32768 >/dev/null
            sudo ethtool -C "$iface" adaptive-rx off rx-usecs 5 rx-frames 1 >/dev/null 2>&1 || true
            for f in /sys/class/net/"$iface"/queues/rx-*/rps_flow_cnt; do
                [[ -e "$f" ]] || continue
                printf "2048\n" | sudo tee "$f" >/dev/null || true
            done
            for f in /sys/class/net/"$iface"/queues/rx-*/rps_cpus; do
                [[ -e "$f" ]] || continue
                printf "fffff\n" | sudo tee "$f" >/dev/null || true
            done
            sudo ethtool -K "$iface" ntuple on >/dev/null 2>&1 || true
        '
    done
}

verify_xl170_paper_hardware() {
    for i in "${!HOSTS[@]}"; do
        log "xl170-verify" "Verifying xl170 paper hardware settings on node$i"
        ssh "node$i" '
            set -euo pipefail
            node_name="$(hostname)"
            iface="ens1f1"
            cpu_model="$(lscpu | awk -F: "/Model name:/ {gsub(/^ +/, \"\", \$2); print \$2; exit}")"
            nic_driver="$(ethtool -i "$iface" 2>/dev/null | awk -F: "/driver:/ {gsub(/^ +/, \"\", \$2); print \$2; exit}")"
            nic_speed="$(ethtool "$iface" 2>/dev/null | awk -F: "/Speed:/ {gsub(/^ +/, \"\", \$2); print \$2; exit}")"
            if [[ "$cpu_model" != *"E5-2640 v4"* && "$cpu_model" != *"E5-2640v4"* ]]; then
                echo "$node_name: unexpected CPU model: $cpu_model" >&2; exit 1
            fi
            if [[ "$nic_driver" != "mlx5_core" ]]; then
                echo "$node_name: unexpected NIC driver: $nic_driver" >&2; exit 1
            fi
            if [[ "$nic_speed" != "25000Mb/s" ]]; then
                echo "$node_name: unexpected NIC speed: $nic_speed" >&2; exit 1
            fi
            mtu="$(ip -o link show "$iface" | awk "{for (i=1;i<=NF;i++) if (\$i==\"mtu\") {print \$(i+1); exit}}")"
            if [[ "$mtu" != "3000" ]]; then
                echo "$node_name: MTU=$mtu, expected 3000" >&2; exit 1
            fi
            governor="$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null || true)"
            if [[ "$governor" != "performance" ]]; then
                echo "$node_name: CPU governor=$governor, expected performance" >&2; exit 1
            fi
            rps_sock="$(sysctl -n net.core.rps_sock_flow_entries 2>/dev/null || echo 0)"
            if [[ "$rps_sock" != "32768" ]]; then
                echo "$node_name: rps_sock_flow_entries=$rps_sock, expected 32768" >&2; exit 1
            fi
            adaptive_rx="$(ethtool -c "$iface" 2>/dev/null | awk -F: "/Adaptive RX:/ {gsub(/^ +/, \"\", \$2); print \$2; exit}")"
            rx_usecs="$(ethtool -c "$iface" 2>/dev/null | awk -F: "/rx-usecs:/ {gsub(/^ +/, \"\", \$2); print \$2; exit}")"
            rx_frames="$(ethtool -c "$iface" 2>/dev/null | awk -F: "/rx-frames:/ {gsub(/^ +/, \"\", \$2); print \$2; exit}")"
            if [[ "$rx_usecs" != "5" || "$rx_frames" != "1" || "$adaptive_rx" != off* ]]; then
                echo "$node_name: coalescing adaptive-rx=$adaptive_rx rx-usecs=$rx_usecs rx-frames=$rx_frames, expected off/5/1" >&2; exit 1
            fi
            ntuple="$(ethtool -k "$iface" 2>/dev/null | awk -F: "/ntuple-filters:/ {gsub(/^ +/, \"\", \$2); print \$2; exit}")"
            if [[ "$ntuple" != "on" ]]; then
                echo "$node_name: ntuple-filters=$ntuple, expected on" >&2; exit 1
            fi
            tso="$(ethtool -k "$iface" 2>/dev/null | awk -F: "/tcp-segmentation-offload:/ {gsub(/^ +/, \"\", \$2); print \$2; exit}")"
            if [[ "$tso" != "on" ]]; then
                echo "$node_name: tcp-segmentation-offload=$tso, expected on" >&2; exit 1
            fi
            for f in /sys/class/net/"$iface"/queues/rx-*/rps_flow_cnt; do
                [[ -e "$f" ]] || continue
                value="$(cat "$f")"
                if [[ "$value" != "2048" ]]; then
                    echo "$node_name: $f=$value, expected 2048" >&2; exit 1
                fi
            done
            for f in /sys/class/net/"$iface"/queues/rx-*/rps_cpus; do
                [[ -e "$f" ]] || continue
                value="$(cat "$f")"
                if [[ "$value" != "fffff" ]]; then
                    echo "$node_name: $f=$value, expected fffff" >&2; exit 1
                fi
            done
            printf "%s: xl170 paper hardware settings OK\n" "$node_name"
        '
    done
}

main() {
    require_cmd ssh
    require_cmd ssh-copy-id
    require_cmd ssh-keygen
    require_cmd awk

    read_hosts
    ensure_local_key
    write_local_ssh_config
    install_local_key_on_nodes
    verify_local_connectivity
    prepare_node0_ssh
    install_node0_key_on_peers
    verify_node0_connectivity
    setup_homa_on_node0
    verify_homa_on_node0
    configure_dctcp
    verify_dctcp
    configure_xl170_paper_hardware
    verify_xl170_paper_hardware

    log "done" "10-node SSH bootstrap complete, Homa utilities are built on node0, DCTCP and xl170 paper hardware settings are configured"
}

main "$@"
